version: '3'

services:
  PerfectSound-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - PerfectSoundnet

    
  PerfectSound-api:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=PerfectSound-sql,1433;Database=PerfectSoundDb;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5010:5010
    networks:
      - PerfectSoundnet
    links:
      - PerfectSound-sql
    depends_on:
      - PerfectSound-sql

networks:
  PerfectSoundnet:
    driver: bridge